"""Template renderer for dynamically-created profiles.

Produces a file map (``rel_path → text``) that JobFactory writes to disk.
The layout mirrors the standard Hermes-hybrid profile structure
(calendar_ops, kk_job):

    profiles/{id}/
    ├── config.yaml
    ├── SOUL.md
    ├── intent_schema.json
    ├── skills/          (empty; user adds later)
    ├── cron/            (empty)
    ├── on_demand/       (empty)
    ├── watchers/        (empty)
    ├── memories/
    │   ├── MEMORY.md
    │   └── USER.md
    ├── sessions/
    └── logs/

Intentionally minimal: new profiles start as "chat-only, no tools". The
user (or a later Refiner pass) fills in skills and on_demand jobs as the
profile's scope solidifies.
"""
from __future__ import annotations

import json
from datetime import datetime, timezone
from typing import Iterable


def render_new_profile(
    *,
    profile_id: str,
    role: str,
    scope_allowed: list[str],
    scope_forbidden: list[str],
    actions: list[str],
) -> dict[str, str]:
    """Return ``{relative_path: file_text}`` for a new profile skeleton."""
    ts = datetime.now(timezone.utc).isoformat(timespec="seconds")
    allowed = scope_allowed or ["일반 대화"]
    forbidden = scope_forbidden or ["허위 정보 생성", "권한 없는 외부 API 호출"]
    act_list = actions or ["chat"]

    return {
        "config.yaml": _render_config(profile_id),
        "SOUL.md": _render_soul(profile_id, role, allowed, forbidden, ts),
        "intent_schema.json": _render_schema(profile_id, act_list),
        "memories/MEMORY.md": _render_memory(profile_id, ts),
        "memories/USER.md": _render_user(profile_id),
        # Marker files to create the directories (git keeps them).
        "skills/.gitkeep": "",
        "cron/.gitkeep": "",
        "on_demand/.gitkeep": "",
        "watchers/.gitkeep": "",
        "sessions/.gitkeep": "",
        "logs/.gitkeep": "",
    }


def _render_config(profile_id: str) -> str:
    return f"""# Auto-generated by Job_Factory. Edit freely.
# Official Hermes schema fields.

agent:
  max_turns: 10
  reasoning_effort: "low"
  tool_use_enforcement: "strict"

model:
  provider: "ollama"
  model: "qwen2.5:14b-instruct"
  # 2026-05-04: cloud fallback removed when OpenAI legacy was purged.
  # 2026-05-06: system_mode wrap guard removed alongside the active/quiet
  # 2-mode deprecation. Cron model selection is now driven by tier_policy
  # in this same config + the profile's runtime settings.

terminal:
  backend: local
  timeout: 60
  persistent_shell: true
  env_passthrough: []

memory:
  memory_enabled: true
  user_profile_enabled: true
  memory_char_limit: 2200
  user_char_limit: 1375

compression:
  enabled: true
  threshold: 0.80
  target_ratio: 0.20
  protect_last_n: 20

approvals:
  mode: "manual"

auxiliary:
  compression:
    provider: "auto"
    timeout: 120
  vision:
    provider: "auto"
    timeout: 120

security:
  redact_secrets: true

mcp_servers: {{}}

skills:
  auto_load: []

x-hermes-hybrid:
  profile_id: "{profile_id}"
  timezone: "Asia/Seoul"
  tier_policy:
    max_tier: "C1"
    prefer_tier: "L2"
    heavy_policy: "never"
    bump_rules: []
  budget:
    cap_usd_per_day: 0.10
    cap_usd_per_run: 0.02
    alert_threshold_ratio: 0.8
  delivery_defaults:
    channel: "webhook"
    on_failure: "retry"
  safety_defaults:
    write_requires_confirmation: true
    write_max_retries: 0
    read_max_retries: 2
    analyze_max_retries: 1
"""


def _render_soul(
    profile_id: str,
    role: str,
    allowed: list[str],
    forbidden: list[str],
    ts: str,
) -> str:
    allowed_md = "\n".join(f"  - 허용: {a}" for a in allowed)
    forbidden_md = "\n".join(f"  - 금지: {f}" for f in forbidden)
    return f"""# Agent SOUL — {profile_id}

공식 Hermes 시스템 프롬프트 슬롯 #1. Job_Factory가 {ts}에 생성.

---

## Identity
너는 **{role}**이다. `{profile_id}` 프로파일의 범위 내에서만 동작한다.

## Scope
{allowed_md}
{forbidden_md}

---

## Response Tone & Format
- 한국어 기본. 기술 용어·고유명사는 원문 유지.
- 근거 없는 단정 금지. 확인 불가한 정보는 "확인 필요"로 표시.
- 결과 섹션은 간결한 섹션 헤더 + 불릿 형식.

## Behavior
1. **확인 게이트**: 외부 쓰기 작업은 반드시 사용자 확인 후 실행.
2. **근거 명시**: 외부 데이터 인용 시 출처 URL 포함.
3. **실패 전파**: 자동 재시도 금지. 실패 원인은 즉시 사용자에게 보고.

---

## Safety Rules

### 1. 범위 엄수
- SOUL.md Scope에 열거되지 않은 동작 수행 금지.
- 의심스러운 요청은 거부하고 확인 요청.

### 2. 데이터 무결성
- 허위/과장 내용 생성 금지.
- 외부 시스템 상태 변경은 확인 게이트 필수.

### 3. 개인정보 처리
- 이메일·전화번호 등 PII는 로그에 마스킹.
- 민감 정보는 MEMORY.md에 저장 금지.

### 4. 긴급 정지
- 3회 연속 인증 실패 시 잡 전체 중단.
- 쓰기 실패 시 재시도 금지, 사용자에게 즉시 보고.

---

## Ledger 기록 원칙
- 모든 외부 호출: tool, args_hash, result_status, latency_ms
- 쓰기 작업: 확인 게이트 여부, 결과 ID
- 민감 정보 저장 금지
"""


def _render_schema(profile_id: str, actions: Iterable[str]) -> str:
    schema = {
        "$schema": "http://json-schema.org/draft-07/schema#",
        "title": f"{profile_id.capitalize()}Intent",
        "description": (
            f"Auto-generated intent schema for profile `{profile_id}`. "
            "Extend `action` enum and required fields as the profile matures."
        ),
        "type": "object",
        "required": ["action"],
        "properties": {
            "action": {
                "type": "string",
                "enum": list(actions),
                "description": "수행할 동작",
            },
            "query": {
                "type": "string",
                "maxLength": 500,
                "description": "사용자 요청 원문 또는 요약",
            },
            "confidence": {
                "type": "number",
                "minimum": 0,
                "maximum": 1,
                "description": "LLM 자체 평가. 0.7 미만이면 재질문.",
            },
            "ambiguous_fields": {
                "type": "array",
                "items": {"type": "string"},
                "description": "추출 실패 필드명",
            },
        },
    }
    return json.dumps(schema, ensure_ascii=False, indent=2) + "\n"


def _render_memory(profile_id: str, ts: str) -> str:
    return f"""# Agent Memory — {profile_id}

공식 Hermes `memories/MEMORY.md`. 2200자 한도.
Job_Factory {ts} 생성.

---

## 환경
- 프로파일: {profile_id}
- 타임존: Asia/Seoul

## 관례
- 첫 운영 단계 — 사용자 피드백을 통해 관례·예외 규칙을 축적하세요.

## 주의할 교훈
(운영하며 누적)
"""


def _render_user(profile_id: str) -> str:
    return f"""# User Profile — {profile_id}

공식 Hermes `memories/USER.md`. 1375자 한도.

---

## 사용자
- (사용자 프로파일 미설정)

## 선호 조건
- (첫 사용 시 질문)

## 커뮤니케이션 톤
- 한국어 정중·간결 기본
- 근거 없는 낙관·비난 금지
"""
