"""W3 — Register jobs/generated/job_candidates.generated.yaml into config/job_factory.yaml.

Inserts (or replaces) the marker block:
    # --- generated job candidates ---
    ...
    # --- end ---
within config/job_factory.yaml as a comment-only section listing the
candidates. The marker block does NOT add to `job_types:` — it is
documentation showing what timer-driven jobs exist outside the chat
job_factory classification.

Usage:
    python scripts/register_generated_jobs.py --dry-run
    python scripts/register_generated_jobs.py --apply --candidates-only --validate
"""
from __future__ import annotations

import argparse
import sys
from datetime import datetime, timezone
from pathlib import Path

import yaml


REPO_ROOT = Path(__file__).resolve().parent.parent
DEFAULT_SRC = REPO_ROOT / "jobs" / "generated" / "job_candidates.generated.yaml"
DEFAULT_DST = REPO_ROOT / "config" / "job_factory.yaml"
MARKER_START = "# --- generated job candidates ---"
MARKER_END = "# --- end ---"


def _validate_cron(expr: str) -> bool:
    parts = (expr or "").split()
    return len(parts) == 5


def _render_block(jobs: list[dict]) -> str:
    lines: list[str] = [
        MARKER_START,
        f"#",
        f"# Generated by scripts/register_generated_jobs.py at "
        f"{datetime.now(timezone.utc).isoformat(timespec='seconds')}.",
        f"# These are timer-driven cron jobs (not chat job_types).",
        f"# Source: jobs/generated/job_candidates.generated.yaml",
        f"#",
    ]
    for j in jobs:
        lines.append(f"#   - id: {j.get('id')}")
        lines.append(f"#     name: {j.get('name')}")
        lines.append(f"#     schedule: {j.get('schedule')}  # {j.get('timezone', 'Asia/Seoul')}")
        lines.append(f"#     status: {j.get('status')}")
        lines.append(f"#     evidence: {j.get('evidence', '')}")
    lines.append(MARKER_END)
    return "\n".join(lines) + "\n"


def _load(src: Path) -> list[dict]:
    with src.open("r", encoding="utf-8") as f:
        data = yaml.safe_load(f) or {}
    return data.get("jobs") or []


def main() -> int:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--src", type=Path, default=DEFAULT_SRC)
    p.add_argument("--dst", type=Path, default=DEFAULT_DST)
    p.add_argument("--candidates-only", action="store_true",
                   help="emit only status=candidate jobs")
    p.add_argument("--validate", action="store_true")
    g = p.add_mutually_exclusive_group()
    g.add_argument("--dry-run", action="store_true", default=True)
    g.add_argument("--apply", action="store_true")
    args = p.parse_args()
    if args.apply:
        args.dry_run = False

    if not args.src.exists():
        print(f"src missing: {args.src}", file=sys.stderr)
        return 1

    jobs = _load(args.src)
    if args.candidates_only:
        jobs = [j for j in jobs if (j.get("status") == "candidate")]

    if args.validate:
        bad = [j for j in jobs if not _validate_cron(j.get("schedule") or "")]
        if bad:
            for j in bad:
                print(f"invalid cron: {j.get('id')} schedule={j.get('schedule')}",
                      file=sys.stderr)
            return 1

    block = _render_block(jobs)

    print(f"src: {args.src}")
    print(f"dst: {args.dst}")
    print(f"jobs: {len(jobs)}")
    print(f"mode: {'apply' if args.apply else 'dry-run'}")

    if args.dry_run:
        print("--- block preview ---")
        print(block)
        return 0

    if not args.dst.exists():
        print(f"dst missing: {args.dst}", file=sys.stderr)
        return 1

    text = args.dst.read_text(encoding="utf-8")
    if MARKER_START in text and MARKER_END in text:
        # Replace existing block
        start = text.index(MARKER_START)
        end = text.index(MARKER_END, start) + len(MARKER_END)
        end_nl = text.find("\n", end)
        if end_nl == -1:
            end_nl = end
        new_text = text[:start] + block + text[end_nl + 1 :]
    else:
        # Append
        if not text.endswith("\n"):
            text += "\n"
        new_text = text + "\n" + block

    args.dst.write_text(new_text, encoding="utf-8")
    print(f"wrote block ({len(jobs)} jobs)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
